import "./globals.css";

import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google'

import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";

export const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-ibm-plex-sans",
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Savvy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased ${ibm_plex_sans.className}`}>
          <QueryProvider>
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
